spring:
  application:
    name: ManagementSystem
  profiles:
    active: dev

server:
  port: 8088

#mybatis-plus配置控制台打印完整带参数SQL语句
mybatis-plus:
  #  configuration:
  #    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:/mapper/*Mapper.xml